name: Release Drafter

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read
  pull-requests: read

jobs:
  update_release_draft:
    name: Update Release Draft
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
    
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Update release draft
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
          publish: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  validate_pr_labels:
    name: Validate PR Labels
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
      - name: Check PR labels
        uses: actions/github-script@v6
        with:
          script: |
            const { data: pullRequest } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });
            
            const labels = pullRequest.labels.map(label => label.name);
            console.log('PR labels:', labels);
            
            // Define required label categories
            const labelCategories = {
              type: ['feature', 'bug', 'enhancement', 'chore', 'documentation', 'security', 'performance'],
              area: ['ui', 'build', 'testing', 'dependencies', 'accessibility']
            };
            
            // Check if PR has at least one type label
            const hasTypeLabel = labelCategories.type.some(label => labels.includes(label));
            
            if (!hasTypeLabel && !labels.includes('skip-changelog')) {
              console.log('⚠️ PR is missing a type label. Consider adding one of:', labelCategories.type.join(', '));
              
              // Add a comment suggesting labels
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: |
                  ## 🏷️ Label Suggestion
                  
                  This PR doesn't have a type label yet. Consider adding one of these labels to help with release notes generation:

                  **Type labels:**
                  - `feature` - New functionality
                  - `enhancement` - Improvements to existing features  
                  - `bug` - Bug fixes
                  - `performance` - Performance improvements
                  - `security` - Security updates
                  - `documentation` - Documentation changes
                  - `chore` - Maintenance tasks

                  **Area labels (optional):**
                  - `ui` - User interface changes
                  - `build` - Build system changes
                  - `testing` - Test-related changes
                  - `dependencies` - Dependency updates
                  - `accessibility` - Accessibility improvements

                  If this PR should not appear in release notes, add the `skip-changelog` label.

                  *This comment was automatically generated by the Release Drafter workflow.*
              });
            } else {
              console.log('✅ PR has appropriate labels or is marked to skip changelog');
            }